development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: ivoted_development
  username: USERNAME
  password: PASSWORD
  
production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: ivoted_production
  username: USERNAME
  password: PASSWORD

test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: ivoted_test
  username: USERNAME
  password: PASSWORD